merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import  views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/',views.band_create, name='band-create'),
    path('bands/<int:id>/update/',views.band_update, name='band-update'),
    path('bands/<int:id>/delete/',views.band_delete,name='band-delete'),
    path('listings/', views.listings, name='listing-list'),
    path('listings/<int:id>/', views.listings_detail, name="listing-detail"),
    path('listings/add/', views.listings_create, name='listing-create'),
    path('listings/<int:id>/', views.listings_by_band , name='listings-by-band'),
    path('listings/<int:id>/update/',views.listings_update, name='listing-update'),
    path('listings/<int:id>/delete/',views.listings_delete,name='listing-delete'),
    path('contact/', views.contact, name='contact-us'),
    path('email_sent',views.email_sent, name="email-sent")
    
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.


class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900),MaxValueValidator(2023)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.name}'


class Listing(models.Model):

    class ListingType(models.TextChoices):
        RECORDS = 'R'
        CLOTHING = 'C'
        POSTERS = 'P'
        MISC = 'M'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        null=True,
        validators=[MinValueValidator(1900),
                    MaxValueValidator(2023)]
    )
    type = models.fields.CharField(choices=ListingType.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing


class ContactUsForm(forms.Form):

    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):

    class Meta:
        model = Band
        fields = '__all__'


class ListingForm(forms.ModelForm):

    class Meta:
        model = Listing
        fields = '__all__'

merchex/listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from listings.models import Band
from listings.models import Listing
from listings.forms import ContactUsForm, BandForm, ListingForm
from django.core.mail import send_mail
from django.shortcuts import redirect


# Create your views here.
def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html',
                  {'bands': bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)

        if form.is_valid():
            band = form.save()
           
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request, 'listings/band_create.html',
                  {'form': form})


def band_update(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                  'listings/band_update.html',
                  {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        band.delete()
        return redirect('band-list')

    return render(request,
                  'listings/band_delete.html',
                  {'band': band})


def listings(request):
    listings = Listing.objects.all()
    return render(request,
                  'listings/listings.html',
                  {'listings': listings})


def listings_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, 
                  'listings/listings_detail.html',
                  {'listing': listing})


def listings_create(request):

    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()

    return render(request, 'listings/listing_create.html',
                  {'form': form})


def listings_by_band(request, id):
    listings = Band.objects.get(id=id).listing_set.all()
    return render(request, 'listings/listings_by_band.html',
                  {'listings': listings})


def listings_update(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request,
                  'listings/listing_update.html',
                  {'form': form})


def listings_delete(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        listing.delete()
        return redirect('listing-list')

    return render(request,
                  'listings/listing_delete.html',
                  {'listing': listing})


def email_sent(request):
    return render(request,
                  'listings/email_sent.html')


def contact(request):

    if request.method == 'POST':

        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via Merchex Contact Us Form',
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email-sent')
        

    else:
        form = ContactUsForm()
    
    return render(request,
           'listings/contact.html',
           {'form': form})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

{% endblock %}
   

merchex/listings/templates/listings/band_create copy.html
{% extends 'listings/base.html' %}

{% block content %}

<h1> Supprimer le groupe</h1>
<p>Etes vous sur de vouloir supprimer le groupe : {{ band.name }} ? </p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>
{% endblock %}
   

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1> Creer un  nouveau groupe</h1>
<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Creer">
</form>
<a href="{% url 'band-list' %}">voir tout les groupes</a>
{% endblock %}
   

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1> Supprimer le groupe</h1>
<p>Etes vous sur de vouloir supprimer le groupe : {{ band.name }} ? </p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>
{% endblock %}
   

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}  

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
 {% if band.official_homepage  %}
 <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li> 
 {% endif %}
</ul>

<p>{{ band.biography }}</p>
<ul>
    <li><a href="{% url 'band-list' %}">retour voir tout les groupes</a></li>
    <li><a href="{% url 'listings-by-band' band.id %}">voir tout les articles  associes a ce groupe</a></li>
    <li><a href="{% url 'band-update' band.id %}">Mettre a jour ce groupe</a></li>
    <li><a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a></li>
</ul>


{% endblock content %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Groupes</h1>
    <ul>
        {% for band in bands %}
        <li> <a href="{% url 'band-detail' band.id  %}">{{ band.name }}</a></li>
        {% endfor %}
        <li> <a href="{% url 'band-create' %}"> creer un nouveau groupe</a></li>
    </ul>
{% endblock %}
   

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1> Mettre a jour le groupe</h1>
<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Mettre a jour">
</form>
<a href="{% url 'band-list' %}">voir tout les groupes</a>
{% endblock %}
   

merchex/listings/templates/listings/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}"/>
    <title>Document</title>
</head>
<body>
    
    {% block content %}{% endblock %}
    
</body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
<p>Le message a bien été envoyé <p>
<a href="{% url 'band-list' %}">retour voir liste de groupes</a>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1> Creer un  nouvel artcile</h1>
<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Creer">
</form>
<a href="{% url 'listing-list' %}">voir la liste des articles</a>
{% endblock %}
   

merchex/listings/templates/listings/listing_delete.html
{% extends "listings/base.html" %}
{% block content %}
<h1> Supprimer l'artcile</h1>
<p> Vous voulez vraiment supprimer cet artcile {{ listing.name}} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="supprimer">
</form>

    
{% endblock content %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1> Mettre a jour l'article</h1>
<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Mettre a jour">
</form>
<a href="{% url 'listing-list' %}">voir la liste des articles</a>
{% endblock %}
   

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

<h1> hello Django</h1>
<p>Mes titres préférés sont :</p>
<ul>
    {% for listing in listings %}
    <a href="{% url 'listing-detail' listing.id  %} "><li>{{listing.title}}</li></a>
    {%endfor%}
    <li><a href="{% url 'band-list' %}">retour voir tout les groupes</a></li>
    <li><a href="{% url 'listing-create' %}">Creer un article</a></li>
</ul>

{% endblock %}

merchex/listings/templates/listings/listings_detail.html
{% extends 'listings/base.html' %}  

{% block content %}
<h2>{{ listing.title }}</h2>

<ul>
 <li>Type : {{ listing.get_type_display }}</li>
 <li>Année de formation : {{ listing.year_formed }}</li>

</ul>

<p>{{ listing.description }}</p>
<a href="{% url 'listing-list' %}">retour voir tout articles</a>
<a href="{% url 'listing-update' listing.id %}">Mettre a jour cet artcile</a>
<a href="{% url 'listing-delete' listing.id %}">Supprimer cet article</a>
{% endblock content %}